# Generated by Django 5.2.8 on 2025-11-25 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_empty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('online', models.ManyToManyField(blank=True, related_name='group_online_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_folder', to='a_chats.chat')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_membership', to='a_chats.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='chats', through='a_chats.ChatMembership', through_fields=['chat', 'user'], to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_empty', models.BooleanField(default=False)),
                ('chats', models.ManyToManyField(related_name='folders', through='a_chats.ChatFolder', through_fields=['folder', 'chat'], to='a_chats.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatfolder',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_chats', to='a_chats.folder'),
        ),
        migrations.AddIndex(
            model_name='chatmembership',
            index=models.Index(fields=['user', 'chat'], name='user_chat_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmembership',
            index=models.Index(condition=models.Q(('is_admin', True)), fields=['chat'], name='is_admin_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmembership',
            index=models.Index(condition=models.Q(('is_member', True)), fields=['chat'], name='is_member_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmembership',
            index=models.Index(condition=models.Q(('is_owner', True)), fields=['chat'], name='is_owner_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmembership',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['name'], name='chat_name_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfolder',
            index=models.Index(fields=['chat', 'folder'], name='chat_folder_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatfolder',
            unique_together={('chat', 'folder')},
        ),
    ]
