# Generated by Django 5.2.8 on 2025-11-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_at']},
        ),
    ]
